### ISSUE TITLE
Why not

### ISSUE THREAD

**Issue by AtariSMN82** [Rookfighter/inifile-cpp#19]
Вы можете использовать такой код (inicpp.h:234)?
void decode(const std::string &value, double &result) {
  std::stringstream stream;
  stream << value;
  stream >> result;
}

**Comment by Rookfighter** [comment]
Hi there,

inifile-cpp tries to avoid the formatted read / write methods of the streams as much as possible, because they are

a) slow
b) can undesired side-effects from stream formatting configurations

So inifile-cpp uses the raw read / write methods to have full control of the input and output format and avoid hard to detect bugs from implict stream dependencies.
