### ISSUE TITLE
Disable sorting

### ISSUE THREAD

**Issue by UnrealKaraulov** [Rookfighter/inifile-cpp#31]
How to disable ALPHABET sorting in output file?

It always broke my file structure...

For example...
```
[General]
NUM_AITEMS = 5
AITEMS_ENABLED = false
[AITEM1]
DATA = X
```
After save it make fully unreadabled:
```
[AITEM1]
DATA = X
[General]
AITEMS_ENABLED = false
NUM_AITEMS = 5
```

**Comment by UnrealKaraulov** [comment]
@Rookfighter maybe need std::unordered_map instead of std::map?

**Comment by Rookfighter** [comment]
Hi @UnrealKaraulov,

Thanks for using `inifile-cpp`.

unfortunately switching to `std::unordered_map` is not an option because both `std::map`and `std::unordered_map` do not preserve the insertion order.

For preserving the insertion order you would have to use `std::vector`, however due to performance considerations that is not a reasonable option.

So I have to admit, that `inifile-cpp` will (also in future) not support the preserving of the insertion order, because the order of the arguments has no effect on the semantic meaning of the file.

The only argument for preserving the order of insertion would be convenience for users when working on inifiles which have been changed by `inifile-cpp`.

However, one note on this: If humans and your programs both read and write to the same inifiles, these kinds of problems (readability, mal-formed files, invalidation of files, data loss) always arise. Maybe it is also an option for you to move the parts of your inifile which are written / modified by humans into a separate ini-file. So contents modified by humans are only read by your program (and not written by the program), then your file will also not suffer from being reformatted.

**Comment by UnrealKaraulov** [comment]
> Hi @UnrealKaraulov,
> 
> Thanks for using `inifile-cpp`.
> 
> unfortunately switching to `std::unordered_map` is not an option because both `std::map`and `std::unordered_map` do not preserve the insertion order.
> 
> For preserving the insertion order you would have to use `std::vector`, however due to performance considerations that is not a reasonable option.
> 
> So I have to admit, that `inifile-cpp` will (also in future) not support the preserving of the insertion order, because the order of the arguments has no effect on the semantic meaning of the file.
> 
> The only argument for preserving the order of insertion would be convenience for users when working on inifiles which have been changed by `inifile-cpp`.
> 
> However, one note on this: If humans and your programs both read and write to the same inifiles, these kinds of problems (readability, mal-formed files, invalidation of files, data loss) always arise. Maybe it is also an option for you to move the parts of your inifile which are written / modified by humans into a separate ini-file. So contents modified by humans are only read by your program (and not written by the program), then your file will also not suffer from being reformatted.

Okay then your project is not usable :(

**Comment by UnrealKaraulov** [comment]
I removed star from this project :(

**Comment by UnrealKaraulov** [comment]
I tried to replace std::map to std::unordered_map and it save 90% of input ini structure. :)

**Comment by Rookfighter** [comment]
> I tried to replace std::map to std::unordered_map and it save 90% of input ini structure. :)

That's true, the order of elements in a hash map might coincide to some extent with the insertion order. However, there is no guarantee about that in the C++ standard (it's even implementation dependent). Depending on the used hashing algorithm, the size of the hash table and the inserted keys, there is no way to get the full 100% for every file under any circumstances.

**Comment by UnrealKaraulov** [comment]
@Rookfighter anyway, your project useless because it not save original structure and comments in ini file....
