### ISSUE TITLE
Restoring the master branch

### ISSUE THREAD

**Issue by kamchatka-volcano** [Rookfighter/inifile-cpp#40]
Hello, my library [`figcone`](https://github.com/kamchatka-volcano/figcone)  depends on  `inifile-cpp`, which is downloaded during CMake configuration using FetchContent. As `inifile-cpp` doesn't provide any version tags, I specified the master branch to download it. Recently (?) the master branch was removed, and it rendered all versions of `figcone` broken unless the user disables the support of the `ini` format. By default, all config formats are supported, so the build is failing during configuration while trying to download `inifile-cpp`. 

It will teach me to only use forked repositories for projects that don't have any versioning, but can you please restore the master branch to fix all previous releases of my library? I'm not asking to make it the main branch again, just to create it in the repo. There were no incompatible changes, so it can be set on the latest commit.

**Comment by Rookfighter** [comment]
Hi @kamchatka-volcano,

first of all thanks for using `inifile-cpp` and sorry for the inconvenience.
You are right, I just renamed the default branch to `main` last week and did not expect it to have such an impact on downstream projects.
I re-added a `master` branch which points to the current HEAD of `main`. However, I won't be able to move this `master` branch alongside the `main` branch, so it will become outdated sooner or later. If you want to keep using the latest `inifile-cpp` version in your downstream projects, I suggest that you update your references to point to `main` instead of `master`, though that's up to you.
Again sorry for the trouble and thanks for reporting.

If the problem has been resolved for you, feel free to close this issue.

**Comment by kamchatka-volcano** [comment]
Thank you!

>I won't be able to move this master branch alongside the main branch, so it will become outdated sooner or later
It's fine, it fixes all previous releases, which is the most important part.

>Again sorry for the trouble and thanks for reporting.
Oh, nevermind, I think it's just a mistake to download dependencies by the branch name. The same issue would happen if you willingly or unwillingly introduced incompatible changes that would break my previous releases. Actually, for me, there's now a positive side that you agreed to create a branch purely for compatibility and it won't be updated later.

That said, have you thought about using version tags? Right now there are none, and I'm thinking of forking `inifile-cpp` to be able to control its version from the libraries that download it. If you would create one, I could just continue using your original repo.
